Trabalho6/fornecedor/urls.py
from django.urls import path

from fornecedor import views

app_name = 'fornecedor'

urlpatterns = [
    path('lista_fornecedor/', views.lista_fornecedor, name='lista_fornecedor'),
    path('cadastra_fornecedor/', views.cadastra_fornecedor, name='cadastra_fornecedor'),
    path('exibe_fornecedor/<int:id>/', views.exibe_fornecedor, name='exibe_fornecedor'),
    path('edita_fornecedor/<int:id>/', views.edita_fornecedor, name='edita_fornecedor'),
    path('remove_fornecedor/', views.remove_fornecedor, name='remove_fornecedor')
]

Trabalho6/produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('lista_produto/', views.lista_produto, name='lista_produto'),
    path('cadastra_produto/', views.cadastra_produto, name='cadastra_produto'),
    path('exibe_produto/<int:id>/', views.exibe_produto, name='exibe_produto'),
    path('edita_produto/<int:id>/', views.edita_produto, name='edita_produto'),
    path('remove_produto/', views.remove_produto, name='remove_produto')
]

Trabalho6/projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from projeto import views, settings

urlpatterns = [
    path('', lambda request: redirect('carrinho/')),
    path('carrinho/', include('carrinho.urls')),
    path('produto/', include('produto.urls')),
    path('fornecedor/', include('fornecedor.urls')),
    path('admin/', admin.site.urls),
    path('autenticacao/', include('autenticacao.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Trabalho6/fornecedor/models.py
from django.db import models


class Fornecedor(models.Model):
    nome = models.CharField(max_length=50, db_index=True, unique=True)
    endereco = models.CharField(max_length=100)
    telefone = models.CharField(max_length=10)
    cnpj = models.IntegerField()
    slug = models.SlugField(max_length=50)

    class Meta:
        db_table = 'fornecedor'
        ordering = ('nome',)

    def __str__(self):
        return self.nome

Trabalho6/fornecedor/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from fornecedor.models import Fornecedor
from projeto import settings


class PesquisaFornecedorForm(forms.Form):

    nome = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'maxlength': '100'}),
        required=False)


class FornecedorForm(forms.ModelForm):

    class Meta:
        model = Fornecedor
        fields = ('nome', 'endereco', 'telefone', 'cnpj')
        localized_fields = ('cnpj',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages={'required': 'Campo obrigatório.',
                                            'unique': 'Nome de fornecedor duplicado.'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['endereco'].error_messages={'required': 'Campo obrigatório'}
        self.fields['endereco'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['telefone'].error_messages = {'required': 'Campo obrigatório'}
        self.fields['telefone'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['cnpj'].error_messages = {'required': 'Campo obrigatório',
                                              'invalid': 'CNPJ invalido'}
        self.fields['cnpj'].widget.attrs.update({'class': 'form-control form-control-sm'})

    def clean_cnpj(self):
        cnpj_lido = self.cleaned_data['cnpj']
        cnpj = str(cnpj_lido)
        if (len(cnpj) != 14):
            raise ValidationError("Quantidade errada de digitos para o CNPJ.")

        digitos_verificadores = cnpj[-2:]  # Pegando os ultimos dois digitos do cnpj
        soma = 0
        lista1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
        lista2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]

        for i in range(len(lista1)):
            soma = soma + int(cnpj[i]) * int(lista1[i])

        resto = soma % 11
        if (resto < 2):
            digito1 = 0
        else:
            digito1 = 11 - resto

        soma = 0
        for i in range(len(lista2)):
            soma = soma + int(cnpj[i]) * int(lista2[i])

        resto = soma % 11
        if (resto < 2):
            digito2 = 0
        else:
            digito2 = 11 - resto

        if (digitos_verificadores == str(digito1) + str(digito2)):
            return cnpj_lido
        else:
            raise ValidationError("CNPJ invalido.")

Trabalho6/fornecedor/views.py
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaultfilters import slugify

from fornecedor.forms import PesquisaFornecedorForm, FornecedorForm
from fornecedor.models import Fornecedor

def lista_fornecedor(request):
    form = PesquisaFornecedorForm(request.GET)
    if form.is_valid():
        nome = form.cleaned_data['nome']
        lista_de_fornecedores = Fornecedor.objects\
                                   .filter(nome__icontains=nome)\
                                   .order_by('nome')

        paginator = Paginator(lista_de_fornecedores, 3)
        pagina = request.GET.get('pagina')
        page_obj = paginator.get_page(pagina)

        print(lista_de_fornecedores)
        print(page_obj)

        return render(request, 'fornecedor/pesquisa_fornecedor.html', { 'fornecedores': page_obj,
                                                                  'form': form,
                                                                  'nome': nome })


        # # Cria um objeto paginator que irá provocar a execução de uma query que irá
        # # retornar apenas os fornecedores de uma determinada página.
        # paginator = Paginator(lista_de_fornecedores, 6)  # Mostra 6 fornecedores por página
        # pagina = request.GET.get('pagina')
        # try:
        #     fornecedores = paginator.page(pagina)
        # except PageNotAnInteger:
        #     # If page is not an integer, deliver first page.
        #     fornecedores = paginator.page(1)
        # except EmptyPage:
        #     # If the request is AJAX and the page is out of range return an empty page
        #     if request.is_ajax():
        #         return HttpResponse('')
        #     # If page is out of range (e.g. 9999), deliver last page of results.
        #     fornecedores = paginator.page(paginator.num_pages)
        #
        # if request.is_ajax():
        #     return render(request, 'vendas/fornecedor/lista_ajax.html', {'fornecedores': fornecedores})
        #
        # return render(request, 'vendas/fornecedor/lista.html', {'categoria': categoria,
        #                                                      'categorias': categorias,
        #                                                      'fornecedores': fornecedores})
    else:
        raise ValueError('Ocorreu um erro inesperado ao tentar recuperar um fornecedor.')


# @user_passes_test(lambda u: u.is_staff)
def cadastra_fornecedor(request):

    if request.POST:
        fornecedor_id = request.session.get('fornecedor_id')
        print('fornecedor_id na sessão = ' + str(fornecedor_id))
        if fornecedor_id:
            fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)
            fornecedor_form = FornecedorForm(request.POST, request.FILES, instance=fornecedor)
        else:
            fornecedor_form = FornecedorForm(request.POST, request.FILES)

        if fornecedor_form.is_valid():
            fornecedor = fornecedor_form.save(commit=False)
            fornecedor.slug = slugify(fornecedor.nome)
            fornecedor.save()
            if fornecedor_id:
                messages.add_message(request, messages.INFO, 'Fornecedor alterado com sucesso!')
                del request.session['fornecedor_id']
            else:
                messages.add_message(request, messages.INFO, 'Fornecedor cadastrado com sucesso!')

            return redirect('fornecedor:exibe_fornecedor', id=fornecedor.id)
    else:
        # if 'fornecedor_id' in request.session:
        #     del request.session['fornecedor_id']
        try:
            del request.session['fornecedor_id']
        except KeyError:
            pass
        fornecedor_form = FornecedorForm()

    return render(request, 'fornecedor/cadastra_fornecedor.html', {'form': fornecedor_form})


# @user_passes_test(lambda u: u.is_staff)
def exibe_fornecedor(request, id):
    fornecedor = get_object_or_404(Fornecedor, pk=id)
    request.session['fornecedor_id_del'] = id
    return render(request, 'fornecedor/exibe_fornecedor.html', {'fornecedor': fornecedor})


# @user_passes_test(lambda u: u.is_staff)
def edita_fornecedor(request, id):
    fornecedor = get_object_or_404(Fornecedor, pk=id)
    fornecedor_form = FornecedorForm(instance=fornecedor)
    request.session['fornecedor_id'] = id
    return render(request, 'fornecedor/cadastra_fornecedor.html', {'form': fornecedor_form})


# @user_passes_test(lambda u: u.is_staff)
def remove_fornecedor(request):
    fornecedor_id = request.session.get('fornecedor_id_del')
    fornecedor = get_object_or_404(Fornecedor, id=fornecedor_id)
    fornecedor.delete()
    del request.session['fornecedor_id_del']
    messages.add_message(request, messages.INFO, 'Fornecedor removido com sucesso.')
    return render(request, 'fornecedor/exibe_fornecedor.html', {'fornecedor': fornecedor})

Trabalho6/fornecedor/templates/fornecedor/cadastra_fornecedor.html
{% extends 'base.html' %}

{% load static %}

   <div class='mb-4'>
      <h5>Cadastro de Fornecedores</h5>
      <hr class='mt-0'>
   </div>

{% block corpo %}
   <form action="{% url 'fornecedor:cadastra_fornecedor' %}" method="POST" class="pb-4"
         enctype="multipart/form-data" novalidate style="min-height: 330px">
      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_nome" class="col-xl-2 font-weight-bold">Nome</label>
               <div class="col-xl-9">
                  {{ form.nome }}
                  {# <input type="text" name="nome" maxlength="100" required="" id="id_nome"> #}
                  {% if form.nome.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.nome.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_endereco" class="col-xl-3 font-weight-bold">Endereco</label>
               <div class="col-xl-9">
                  {{ form.endereco }}
                  {# <input type="text" name="endereco" maxlength="100" required="" id="id_endereco"> #}
                  {% if form.endereco.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.endereco.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-xl-3">
         <div class="col-xl-6">
            <div class="row">
               <label for="id_telefone" class="col-xl-2 font-weight-bold">Telefone</label>
               <div class="col-xl-9">
                  {{ form.telefone }}
                  {# <input type="text" name="telefone" maxlength="10" required="" id="id_telefone"> #}
                  {% if form.telefone.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.telefone.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
         <div class="col-xl-6">
            <div class="row">
               <label for="id_cnpj" class="col-xl-3 font-weight-bold">CNPJ</label>
               <div class="col-xl-9">
                  {{ form.cnpj }}
                  {# <input type="number" name="cnpj" value="0" required="" id="id_cnpj"> #}
                  {% if form.cnpj.errors %}
                     <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.cnpj.errors %}
                           <small>{{ error }}</small>
                        {% endfor %}
                     </div>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>

      <div class="row mb-5">
         <div class="col-xl-6">
            <div class="row">
               <div class="col-xl-10 offset-xl-2">
                  {% csrf_token %}
                  <button id="botao" type="submit" class="btn btn-primary">
                     {% if 'fornecedor_id' in request.session %}
                        <img src="{% static 'images/skin/database_edit.png' %}"> Alterar
                     {% else %}
                        <img src="{% static 'images/skin/database_add.png' %}"> Cadastrar
                     {% endif %}
                  </button>
               </div>
            </div>
         </div>
      </div>

   </form>
{% endblock %}

Trabalho6/fornecedor/templates/fornecedor/exibe_fornecedor.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Cadastro de Fornecedores
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Cadastro de Fornecedores</h5>
      <hr class='mt-0'>
   </div>

   <div style="min-height: 330px">
      {% if messages %}
         <div class="mb-3">
            {% for message in messages %}
               <ul class="list-group rounded">
                  <li style="padding-top: 7px; padding-bottom: 7px"
                      class="list-group-item list-group-item-info">
                     {{ message }}
                  </li>
               </ul>
            {% endfor %}
         </div>
      {% endif %}

      <div class="row mb-3">
         <div class="col-lg-9 col-md-8">
            <div class="row">
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Nome</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ fornecedor.nome }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Endereco</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ fornecedor.endereco }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">Telefone</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ fornecedor.telefone }}</div>
               <div class="col-xl-2 col-lg-3 col-4 font-weight-bold mb-1">CNPJ</div>
               <div class="col-xl-10 col-lg-9 col-8">{{ fornecedor.cnpj }}</div>
            </div>
         </div>
      </div>

      {% if fornecedor.id %}
         <div class="form-group row">
            <div class="col-12">
               <div class="form-inline">
                  <a href="{% url 'fornecedor:edita_fornecedor' fornecedor.id %}" class="btn btn-primary mr-3">
                     <img src="{% static 'images/skin/database_edit.png' %}" /> Editar
                  </a>

                  <form action="{% url 'fornecedor:remove_fornecedor' %}" method="POST">
                     {% csrf_token %}
                     <button type="submit" class="btn btn-danger">
                        <img src="{% static 'images/skin/database_delete.png' %}"> Remover
                     </button>
                  </form>
               </div>
            </div>
         </div>
      {% endif %}
   </div>
{% endblock %}

Trabalho6/fornecedor/templates/fornecedor/pesquisa_fornecedor.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Pesquisa de Fornecedores
{% endblock %}

{% block corpo %}
   <div class='mb-4'>
      <h5>Pesquisa de Fornecedores</h5>
      <hr class='mt-0'>
   </div>

   <form action="" method ='GET' class="mb-4">
      <div class='form-group row' style='margin-bottom: 10px;'>
         <label for='id_nome' class='col-lg-2 col-form-label font-weight-bold'>
            Nome
         </label>
         <div class='col-lg-10'>
            {{ form.nome }}
            <!--
            <input type='text' name='nome' id='id_nome' class='form-control form-control-sm' maxlength='100'>
            -->
         </div>
      </div>
      <div class='form-group row'>
         <div class="col-lg-10 offset-lg-2">
            <button type='submit' class='btn btn-primary'>
               <div class="d-flex align-items-center">
                  <img src="{% static 'images/skin/binoculo.png' %}" class="mr-2">Pesquisar
               </div>
            </button>
         </div>
      </div>
   </form>

   <div style="min-height: 212px">
      {% if fornecedores %}
         <h5 class="mb-3">Lista de Fornecedores</h5>
         <table style='width:100%'
                class='table table-striped table-sm table-bordered table-responsive mb-4'>
            <thead>
               <tr>
                  <th class='text-center'>Nome</th>
                  <th class="text-center">Endereco</th>
                  <th class='text-center'>Telefone</th>
                  <th class="text-center">CNPJ</th>
               </tr>
            </thead>
            <tbody>
               {% for fornecedor in fornecedores %}
                  <tr>
                     <td width="25%" class="text-center align-middle">
                        {{ fornecedor.nome }}
                     </td>
                     <td width="25%" class="text-center align-middle">
                        {{ fornecedor.endereco }}
                     </td>
                     <td width="25%" class="text-center align-middle">
                        {{ fornecedor.telefone }}
                     </td>
                     <td width="25%" class="text-right align-middle pr-3">
                        {{ fornecedor.cnpj }}
                     </td>
                  </tr>
               {% endfor %}
            </tbody>
         </table>

         <div style='font-size: 14px; margin-bottom: 28px'>
            {% if fornecedores.has_other_pages %}
               <ul class='pagination'>
                  {% if fornecedores.has_previous %}
                     <li class='page-item'><a class='page-link' href='?pagina={{ fornecedores.previous_page_number }}&nome={{nome}}'>Anterior</a></li>
                  {% else %}
                     <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Anterior</a></li>
                  {% endif %}
                  {% for i in fornecedores.paginator.page_range %}
                     {% if fornecedores.number == i %}
                        <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
                     {% else %}
                        <li class='page-item'><a class='page-link' href='?pagina={{ i }}&nome={{nome}}'>{{ i }}</a></li>
                     {% endif %}
                  {% endfor %}
                  {% if fornecedores.has_next %}
                     <li class='page-item'><a class='page-link' href='?pagina={{ fornecedores.next_page_number }}&nome={{nome}}'>Próxima</a></li>
                  {% else %}
                     <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Próxima</a></li>
                  {% endif %}
               </ul>
            {% endif %}
         </div>
      {% endif %}
   </div>

{% endblock %}